// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jednyqvexkcrwxubxici.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZG55cXZleGtjcnd4dWJ4aWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjMxOTIsImV4cCI6MjA2Nzg5OTE5Mn0.lP_JsX-G5xxJwDCa9tpVGCx_34yrycOJbzMjs7ADhT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});